import SectionAbout from '@/components/landing/SectionAbout'
import HeroLandingPage from '@/components/landing/hero'
import MainLayout from '@/layouts/MainLayout'
import { Box } from '@chakra-ui/react'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <Box px={{ base: 5, lg: '10rem' }}>
            <HeroLandingPage />
          </Box>
          <SectionAbout />
        </MainLayout>
      </main>
    </>
  )
}
